name: china_prices
description: A modern Flutter web app for comparing prices across Chinese e-commerce platforms
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Design
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0

  # State Management
  provider: ^6.1.1

  # Web-compatible storage
  shared_preferences: ^2.2.2

  # Web-compatible image handling
  dio: ^5.3.2

  # Web routing
  go_router: ^13.2.0

  # Web notifications
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/data/
